<?xml version="1.0"?>
<package format="3">
  <name>person_zone_cpp</name>
  <version>1.0.0</version>
  <description>ROS-free three-zone core with ROS 2 XYZ and safety adapter.</description>
  <maintainer email="qdsaxz05@gmail.com">OIH62</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_srvs</depend>
  <depend>person_pose_msgs</depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>person_pose</exec_depend>
  <exec_depend>person_zone_debug</exec_depend>
  <test_depend>ament_cmake_gtest</test_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
